package shiftscope.views;

import java.awt.Color;
import java.awt.Graphics2D;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JLayer;
import javax.swing.filechooser.FileFilter;
import shiftscope.main.Main;
import shiftscope.utils.MainScreen;
import shiftscope.utils.StoryBoard;

/**
 *
 * @author Carlos
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form ShiftScopeMain
     */
    private MainScreen mainScreen;
    private Graphics2D g;
    
    public MainView() {
        initComponents();
        setSize(700,500);
        setLocationRelativeTo(null);
        setTitle("ShiftScope");
        setIconImage(new ImageIcon("imgs/icon.png").getImage());
        paint();
        mainScreen = new MainScreen();
        StoryBoard.addScene(mainScreen);
    }
    
    
    private void paint() {
        
        Thread paintThread = new Thread(new Runnable(){
            @Override
            public void run() {
                canvas1.createBufferStrategy(2);
                int i = 0;
                while (true) {
                    g = (Graphics2D) canvas1.getBufferStrategy().getDrawGraphics();
                    g.setColor(Color.BLACK);
                    g.clearRect(0, 0, canvas1.getWidth(), canvas1.getHeight());
                    StoryBoard.paintScene(g);
                    canvas1.getBufferStrategy().show();
                    try {
                        Thread.sleep(30);
                    } catch (InterruptedException ex) {
                        
                    }
                }

            }
        });
        paintThread.start();
    }
    
    public static void findMusic() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        FileFilter fileFilter = new FileFilter() {

            @Override
            public boolean accept(File f) {
                if (f.isDirectory()) {
                    return true;
                }
                return false;
            }

            @Override
            public String getDescription() {
                return ".mp3";
            }
        };
        fileChooser.setFileFilter(fileFilter);
        
        if (fileChooser.showOpenDialog(new JLabel()) == JFileChooser.APPROVE_OPTION) {
            Main.ROOT = fileChooser.getSelectedFile().getAbsolutePath();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        canvas1 = new java.awt.Canvas();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        canvas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                canvas1MouseClicked(evt);
            }
        });
        canvas1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                canvas1ComponentResized(evt);
            }
        });
        canvas1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                canvas1MouseMoved(evt);
            }
        });
        getContentPane().add(canvas1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void canvas1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_canvas1ComponentResized
        
    }//GEN-LAST:event_canvas1ComponentResized

    private void canvas1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvas1MouseMoved
        StoryBoard.mouseMoved(evt.getX(), evt.getY());
        
    }//GEN-LAST:event_canvas1MouseMoved

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
       StoryBoard.setWidth(evt.getComponent().getWidth());
       StoryBoard.setHeight(evt.getComponent().getHeight());
    }//GEN-LAST:event_formComponentResized

    private void canvas1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvas1MouseClicked
        StoryBoard.mousePressed(evt.getX(), evt.getY());
    }//GEN-LAST:event_canvas1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Canvas canvas1;
    // End of variables declaration//GEN-END:variables
}
